apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-app
data:
  POSTGRES_DB: postgres-db
  POSTGRES_USER: postgres-user
  POSTGRES_PASSWORD: postgres-password
