apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  user: "postgres-user"
  password: "postgres-password"
  database: "postgres-db"
  superuser: "admin"
  superuser-password: "admin-password"
